### Get all books
GET http://localhost:8083/books
Content-Type: application/json

### Create book
POST http://localhost:8083/books
Content-Type: application/json

{
  "title": "Livro Full Stack",
  "author": "Fulano de tal",
  "genre": "Tecnologia"
}

### Update book
PUT http://localhost:8083/books/1
Content-Type: application/json

{
  "title": "Lord of Rings",
  "author": "J.R.R Tolkien",
  "genre": "Fantasy"
}

### Delete book
DELETE http://localhost:8083/books/1
